version: '3'

services:
    postgresql:
        image: postgres
        container_name: postgres-container
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=developer
            - POSTGRES_DATABASE=developer
        command: postgres
        restart: always

    redis:
        image: redis:alpine3.14
        container_name: redis-container
        ports:
            - '6379-6379'